config/routes.rb
Rails::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  # resources :jobs do
  #   resources :bids
  # end
  
  resources :employers, :only => [:show, :new, :create] do
    resources :jobs
  end
  
  resources :workers, :only => [:show, :new, :create] do
    resources :jobs
  end
  
  match '/api/skills' => 'xhr#skills'
    
  root :to => "landing#show"
end

app/models/ability.rb
class Ability
  include CanCan::Ability
  
  def initialize(user)
    user ||= User.new
    if user.admin?
      can :manage, :all
    else
      if user.employer?
        can :create, Job
        can :update, Job do |job|
          job.try(:employer) == user.owner && job.draft?
        end
        can :publish, Job do |job|
          job.try(:employer) == user.owner
        end
      end
      if user.worker?
        can :create, Bid
      end
      can :read, Job
    end
  end
end

app/models/assigment.rb
class Assigment < ActiveRecord::Base
  belongs_to :job
  belongs_to :worker
  validates_presence_of :job_id, :worker_id
end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  attr_accessible :user_id, :uid, :provider
  
  belongs_to :user
end

app/models/bid.rb
class Bid < ActiveRecord::Base
  belongs_to :worker
  belongs_to :job
  
  validates_presence_of :price, :pricing_method, :worker_id, :job_id
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates_presence_of :name, :description
  
  has_one :job
  has_many :skills
  has_many :subcategories, :class_name => 'Category', :foreign_key => 'category_id'
  
  scope :main, :conditions => { :category_id => nil }
  
end

app/models/employer.rb
class Employer < ActiveRecord::Base
  has_many :jobs
  has_many :bids, :through => :jobs
  has_one :user, :as => :owner
  
  validates_presence_of :full_name, :company_name, :address1
  accepts_nested_attributes_for :jobs    
end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :employer
  
  belongs_to :category
  has_one :assigment
  has_many :bids
  has_many :employers, :through => :assigments
  has_many :milestones
  accepts_nested_attributes_for :milestones, :reject_if => proc { |attributes| attributes['title'].blank? }
  
  validates_presence_of :title, :description, :start_time, 
        :end_time, :budget, :category_id, :project_begin, :project_finish
        
  validate :time_interval
  
  validates_each :start_time, :end_time do |record, attr, value|
    record.errors.add attr, 'is in the past' unless value.future? || value.today?
  end
  
  def time_interval
    errors.add_to_base 'No ending date must be prior to the starting date' \
       if (end_time.to_date <= start_time.to_date) || (project_finish.to_date <= project_begin.to_date)
  end
  
  scope :current, :conditions => ['start_time <= ? and end_time >= ?', Date.today, Date.today], :include => [:bids]
  
  def self.search(search)
    current.all.where(['title LIKE ?', "%#{search}%"])
  end
end

app/models/milestone.rb
class Milestone < ActiveRecord::Base
  # fields: title, description, start_date, end_date, budget_porcentage
  belongs_to :job
  
  validates_presence_of :title, :description, :start_date, :end_date
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  belongs_to :category
  
  has_many :skill_workers
  has_many :workers, :through => :skill_workers
end

app/models/skill_worker.rb
class SkillWorker < ActiveRecord::Base
  belongs_to :worker
  belongs_to :skill
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :omniauthable

  attr_accessible :email, :password, :password_confirmation, :remember_me, 
                  :owner_type, :owner_id, :admin
                  
  belongs_to :owner, :polymorphic => true
  has_many :authentications, :dependent => :destroy
    
  # Validar que tenga owner si el usuario no es admin
  #validates_presence_of :owner_type, :on => :create, :if => Proc.new {|user| !user.admin }
  
  def apply_omniauth(omniauth)
    self.password = Devise.friendly_token[0,20] if self.password.blank?
    self.email = omniauth['user_info']['email'] if self.email.blank?
    self.authentications.build(:provider => omniauth['provider'], :uid => omniauth['uid'])
  end
  
  def worker?
    true unless owner_type != 'Worker'
  end
  
  def employer?
    true unless owner_type != 'Employer'
  end
  
  def guest?
    true unless owner_type
  end
  
  def admin?
    true unless !admin
  end
end

app/models/worker.rb
class Worker < ActiveRecord::Base
  has_many :bids
  has_many :employers, :through => :bids
  has_one :user, :as => :owner
  
  has_many :assigments
  has_many :jobs, :through => :assigments
  
  has_many :skill_workers
  has_many :skills, :through => :skill_workers
  accepts_nested_attributes_for :skill_workers, :allow_destroy => true
  
  validates_presence_of :full_name
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController  
  def index
    if params[:search]
      @jobs = Job.search(params[:search])
    else
      @jobs = Job.current
    end
  end

  def show
    @job = Job.find(params[:id], :include => [:employer, :category])
  end

  def new
    @job = Job.new
    @job.build_employer
  end

  def edit
    @job = Job.find(params[:id])
  end

  def create
    if @job.save
      flash[:notice] = 'Job was successfully created.'
      redirect_to(@job)
    else
      render :action => "new"
    end
  end

  def update
    @job = Job.find(params[:id])
    
    if @job.update_attributes(params[:job])
      flash[:notice] = 'Job was successfully updated.'
      redirect_to @job
    else
      render :action => "edit"
    end
  end

  def destroy
    @job = Job.find(params[:id])
    @job.destroy

    redirect_to jobs_url
  end
  
  def publish
    @job = Job.find(params[:id])
    if @job.publish
      flash[:notice] = 'Job published successfully'
      redirect_to root_url
    end
  end
end

app/controllers/xhr_controller.rb
class XhrController < ApplicationController
  def skills
    @skills = Skill.all.where(['LOWER(name) LIKE LOWER(?)',"#{params[:name]}%"]).map {|s| [s.id, s.name]}
    render :json => @skills
  end
end

app/helpers/activations_helper.rb
module ActivationsHelper
end

app/helpers/application_helper.rb
# Methods added to this helper will be available to all templates in the application.
module ApplicationHelper
  def remote_jquery_ui(version)
    if Rails.env == 'development'
      "'jqueryui', '#{version}', {uncompressed:true}"
    else
      "'jqueryui', '#{version}'"
    end
  end

  def local_jquery_ui(version)
    if Rails.env == 'development'
      "#{version}/jquery-ui.js"
    else
      "#{version}/jquery-ui.min.js"
    end
  end
end

app/helpers/bids_helper.rb
module BidsHelper
end

app/helpers/employers_helper.rb
module EmployersHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end
  
  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:custom_scripts) { javascript_include_tag(*args) }
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/helpers/xhr_helper.rb
module XhrHelper
end

app/views/jobs/_job_index.html.erb
<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Category</th>
    <th>Ends</th>
    <th>Remaining</th>
    <th>Location</th>
    <th>Budget</th>
    <th>Employer</th>
    <th>Status</th>
  </tr>
<%= @jobs.each do |job| -%>
  <tr>
    <td><%=h job.title %></td>
    <td><%=h job.description %></td>
    <td><%=h job.category.name %></td>
    <td><%=h job.end_time %></td>
    <td><%=h distance_of_time_in_words(Time.now, job.end_time) %>
    <td><%=h job.location %></td>
    <td><%=h job.budget %></td>
    <td><%=h job.employer.full_name %></td>
    <td><%=h job.state.capitalize %></td>
	<td><%= link_to 'Bid', new_job_bid_path(job) %></td>
	<td><%= link_to 'Show', job %></td>
	<% if can? :update, job -%>s
	<% if job.draft? -%>
	<td><%= link_to 'Publish', :controller => 'jobs', :action => 'publish', :id => job.id %></td>
	<% end -%>
    <td><%= link_to 'Edit', edit_job_path(job) %></td>
    <td><%= link_to 'Destroy', job, :confirm => 'Are you sure?', :method => :delete %></td>
    <% end -%>
    
  </tr>
<% end -%>
</table>

app/views/jobs/edit.html.erb
<h1>Editar trabajo</h1>

<%= form_for(@job) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </p>
  <p>
    <%= f.label :start_time %><br />
    <%= f.date_select :start_time %>
  </p>
  <p>
    <%= f.label :end_time %><br />
    <%= f.date_select :end_time %>
  </p>
  <p>
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </p>
  <p>
    <%= f.label :budget %><br />
    <%= f.text_field :budget %>
  </p>
  <p>
    <%= f.label :pricing_method %><br />
    <%= f.text_field :pricing_method %>
  </p>
  <p>
    <%= f.label :service_contact %><br />
    <%= f.text_field :service_contact %>
  </p>
  <p>
    <%= f.label :buyers_support_contact %><br />
    <%= f.text_field :buyers_support_contact %>
  </p>
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<h1>Listado de Trabajos</h1>

<%= render :partial => 'job_index' %>


<% if can? :create, Job %>
<%= link_to 'New job', new_job_path %>
<% end %>

app/views/jobs/new.html.haml
= simple_form_for @job do |f|
  %h3 Please, fill in your company information
  = f.association :employer do |e|
    = e.input     :full_name
    = e.input     :company_name
    = e.input     :address1
  %h3 Next, fill in the job details
  = f.input       :title
  = f.input       :description
  = f.input       :start_time
  = f.input       :end_time
  = f.input       :project_begin
  = f.input       :project_finish
  = f.input       :category_id, :collection => Category.all
  = f.input       :location
  = f.input       :budget
  = f.input       :pricing_method
  = f.input       :service_contact
  = f.input       :buyers_support_contact

  = f.button :submit

app/views/jobs/show.html.erb
<p>
  <b>Title:</b>
  <%=h @job.title %>
</p>

<p>
  <b>Description:</b>
  <%=h @job.description %>
</p>

<p>
  <b>Start time:</b>
  <%=h @job.start_time %>
</p>

<p>
  <b>End time:</b>
  <%=h @job.end_time %>
</p>

<p>
  <b>Location:</b>
  <%=h @job.location %>
</p>

<p>
  <b>Budget:</b>
  <%=h @job.budget %>
</p>

<p>
  <b>Pricing method:</b>
  <%=h @job.pricing_method %>
</p>

<p>
  <b>Service contact:</b>
  <%=h @job.service_contact %>
</p>

<p>
  <b>Buyers support contact:</b>
  <%=h @job.buyers_support_contact %>
</p>

<p>
  <b>Employer:</b>
  <%=h @job.employer.full_name %>
</p>

<% unless @job.bids.empty? %>
<h2>Bids</h2>
<%= render :partial => 'bids/bid_index', :object => @job.bids %>
<% end %>

<%= link_to 'Adjust details', edit_job_path(@job) %>