config/routes.rb
Rails::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  # resources :jobs do
  #   resources :bids
  # end
  
  resources :employers, :only => [:show, :new, :create] do
    resources :jobs
  end
  
  resources :workers, :only => [:show, :new, :create] do
    resources :jobs
  end
  
  match '/api/skills' => 'xhr#skills'
    
  root :to => "landing#show"
end

app/models/ability.rb
class Ability
  include CanCan::Ability
  
  def initialize(user)
    user ||= User.new
    if user.admin?
      can :manage, :all
    else
      if user.employer?
        can :create, Job
        can :update, Job do |job|
          job.try(:employer) == user.owner && job.draft?
        end
        can :publish, Job do |job|
          job.try(:employer) == user.owner
        end
      end
      if user.worker?
        can :create, Bid
      end
      can :read, Job
    end
  end
end

app/models/assigment.rb
class Assigment < ActiveRecord::Base
  belongs_to :job
  belongs_to :worker
  validates_presence_of :job_id, :worker_id
end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  attr_accessible :user_id, :uid, :provider
  
  belongs_to :user
end

app/models/bid.rb
class Bid < ActiveRecord::Base
  belongs_to :worker
  belongs_to :job
  
  validates_presence_of :price, :pricing_method, :worker_id, :job_id
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates_presence_of :name, :description
  
  has_one :job
  has_many :skills
  has_many :subcategories, :class_name => 'Category', :foreign_key => 'category_id'
  
  scope :main, :conditions => { :category_id => nil }
  
end

app/models/employer.rb
class Employer < ActiveRecord::Base
  has_many :jobs
  has_many :bids, :through => :jobs
  has_one :user, :as => :owner
  
  validates_presence_of :full_name, :company_name, :address1
  accepts_nested_attributes_for :jobs    
end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :employer
  
  belongs_to :category
  has_one :assigment
  has_many :bids
  has_many :employers, :through => :assigments
  has_many :milestones
  accepts_nested_attributes_for :milestones, :reject_if => proc { |attributes| attributes['title'].blank? }
  
  validates_presence_of :title, :description, :start_time, 
        :end_time, :budget, :category_id, :project_begin, :project_finish
        
  validate :time_interval
  
  validates_each :start_time, :end_time do |record, attr, value|
    record.errors.add attr, 'is in the past' unless value.future? || value.today?
  end
  
  def time_interval
    errors.add_to_base 'No ending date must be prior to the starting date' \
       if (end_time.to_date <= start_time.to_date) || (project_finish.to_date <= project_begin.to_date)
  end
  
  scope :current, :conditions => ['start_time <= ? and end_time >= ?', Date.today, Date.today], :include => [:bids]
  
  def self.search(search)
    current.all.where(['title LIKE ?', "%#{search}%"])
  end
end

app/models/milestone.rb
class Milestone < ActiveRecord::Base
  # fields: title, description, start_date, end_date, budget_porcentage
  belongs_to :job
  
  validates_presence_of :title, :description, :start_date, :end_date
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  belongs_to :category
  
  has_many :skill_workers
  has_many :workers, :through => :skill_workers
end

app/models/skill_worker.rb
class SkillWorker < ActiveRecord::Base
  belongs_to :worker
  belongs_to :skill
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :omniauthable

  attr_accessible :email, :password, :password_confirmation, :remember_me, 
                  :owner_type, :owner_id, :admin
                  
  belongs_to :owner, :polymorphic => true
  has_many :authentications, :dependent => :destroy
    
  # Validar que tenga owner si el usuario no es admin
  #validates_presence_of :owner_type, :on => :create, :if => Proc.new {|user| !user.admin }
  
  def apply_omniauth(omniauth)
    self.password = Devise.friendly_token[0,20] if self.password.blank?
    self.email = omniauth['user_info']['email'] if self.email.blank?
    self.authentications.build(:provider => omniauth['provider'], :uid => omniauth['uid'])
  end
  
  def worker?
    true unless owner_type != 'Worker'
  end
  
  def employer?
    true unless owner_type != 'Employer'
  end
  
  def guest?
    true unless owner_type
  end
  
  def admin?
    true unless !admin
  end
end

app/models/worker.rb
class Worker < ActiveRecord::Base
  has_many :bids
  has_many :employers, :through => :bids
  has_one :user, :as => :owner
  
  has_many :assigments
  has_many :jobs, :through => :assigments
  
  has_many :skill_workers
  has_many :skills, :through => :skill_workers
  accepts_nested_attributes_for :skill_workers, :allow_destroy => true
  
  validates_presence_of :full_name
end

app/controllers/employers_controller.rb
class EmployersController < ApplicationController
  def show
    @employer = Employer.find(params[:id])
  end

  def new
    @employer = Employer.new
    @employer.jobs.build
  end

  def create
    unless current_user
      session[:employer] = Employer.new params[:employer]
      flash[:notice] = 'Please sign-in to let us know who you are.'
      redirect_to new_user_session_path
    else
      render :action => 'new'
    end
  end
end

app/controllers/xhr_controller.rb
class XhrController < ApplicationController
  def skills
    @skills = Skill.all.where(['LOWER(name) LIKE LOWER(?)',"#{params[:name]}%"]).map {|s| [s.id, s.name]}
    render :json => @skills
  end
end

app/helpers/activations_helper.rb
module ActivationsHelper
end

app/helpers/application_helper.rb
# Methods added to this helper will be available to all templates in the application.
module ApplicationHelper
  def remote_jquery_ui(version)
    if Rails.env == 'development'
      "'jqueryui', '#{version}', {uncompressed:true}"
    else
      "'jqueryui', '#{version}'"
    end
  end

  def local_jquery_ui(version)
    if Rails.env == 'development'
      "#{version}/jquery-ui.js"
    else
      "#{version}/jquery-ui.min.js"
    end
  end
end

app/helpers/bids_helper.rb
module BidsHelper
end

app/helpers/employers_helper.rb
module EmployersHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end
  
  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:custom_scripts) { javascript_include_tag(*args) }
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/helpers/xhr_helper.rb
module XhrHelper
end

app/views/employers/index.html.erb
<h1>Listing employers</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Company name</th>
    <th>Address1</th>
    <th>Address2</th>
    <th>City</th>
    <th>State</th>
    <th>Zip code</th>
    <th>Country</th>
    <th>User</th>
    <th>Phone</th>
    <th>Pay method</th>
  </tr>

<%= @employers.each do |employer| %>
  <tr>
    <td><%=h employer.full_name %></td>
    <td><%=h employer.company_name %></td>
    <td><%=h employer.address1 %></td>
    <td><%=h employer.address2 %></td>
    <td><%=h employer.city %></td>
    <td><%=h employer.state %></td>
    <td><%=h employer.zip_code %></td>
    <td><%=h employer.country %></td>
    <td><%=h employer.user_id %></td>
    <td><%=h employer.phone %></td>
    <td><%=h employer.pay_method %></td>
    <td><%= link_to 'Show', employer %></td>
    <td><%= link_to 'Edit', edit_employer_path(employer) %></td>
    <td><%= link_to 'Destroy', employer, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New employer', new_employer_path %>

app/views/employers/new.html.erb
<h1>New employer</h1>

<%= form_for(@employer) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </p>
  <p>
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </p>
  <p>
    <%= f.label :company_name %><br />
    <%= f.text_field :company_name %>
  </p>
  <p>
    <%= f.label :address1 %><br />
    <%= f.text_field :address1 %>
  </p>
  <p>
    <%= f.label :address2 %><br />
    <%= f.text_field :address2 %>
  </p>
  <p>
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </p>
  <p>
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </p>
  <p>
    <%= f.label :zip_code %><br />
    <%= f.text_field :zip_code %>
  </p>
  <p>
    <%= f.label :country %><br />
    <%= f.text_field :country %>
  </p>
  <p>
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </p>
  <p>
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </p>
  <p>
    <%= f.label :pay_method %><br />
    <%= f.text_field :pay_method %>
  </p>
  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

<%= link_to 'Back', employers_path %>

app/views/employers/new.html.haml
= simple_form_for @employer do |employer|
  %h3 Please, fill in your company information
  = employer.input     :full_name
  = employer.input     :company_name
  = employer.input     :address1
  %h3 Next, fill in the job details
  = employer.association :jobs do |job|
    = job.input       :title
    = job.input       :description
    = job.input       :start_time
    = job.input       :end_time
    = job.input       :project_begin
    = job.input       :project_finish
    = job.input       :category_id, :input_html => { :value => params[:job_category] }, :as => :hidden
    = job.input       :location
    = job.input       :budget
    = job.input       :pricing_method
    = job.input       :service_contact
    = job.input       :buyers_support_contact

  = employer.button :submit

app/views/employers/new.old.erb
<h1>New employer</h1>

<%= form_for(@employer) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :full_name %><br />
    <%= f.text_field :full_name %>
  </p>
  <p>
    <%= f.label :company_name %><br />
    <%= f.text_field :company_name %>
  </p>
  <p>
    <%= f.label :address1 %><br />
    <%= f.text_field :address1 %>
  </p>
  <p>
    <%= f.label :address2 %><br />
    <%= f.text_field :address2 %>
  </p>
  <p>
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </p>
  <p>
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </p>
  <p>
    <%= f.label :zip_code %><br />
    <%= f.text_field :zip_code %>
  </p>
  <p>
    <%= f.label :country %><br />
    <%= f.text_field :country %>
  </p>
  <p>
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </p>
  <p>
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </p>
  <p>
    <%= f.label :pay_method %><br />
    <%= f.text_field :pay_method %>
  </p>
  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

<%= link_to 'Back', employers_path %>

app/views/employers/show.html.haml
%b 
  First name
  = @employer.full_name
%br
%b 
  Company Name
  = @employer.company_name
%br
%b 
  Address
  = @employer.address1
  
- unless @employer.jobs.empty?
  %table
    %thead
      %th Title
      %th Description
      %th Start Time
      %th End Time
    - @employer.jobs.each do |job|
      %tr
        %td= job.title
        %td= job.description
        %td= job.start_time
        %td= job.end_time